# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 12:03
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIMESTAMP_AS_ID', models.CharField(max_length=20)),
                ('EMAIL', models.CharField(max_length=50)),
                ('PHONE', models.CharField(max_length=15)),
                ('FILENAME', models.CharField(max_length=50)),
                ('FILE', django_mysql.models.SizedBinaryField(size_class=4, verbose_name=3)),
                ('STATUS', models.CharField(default='SUBMITTED', max_length=15)),
                ('CLOSEDON', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
